newspaper_project/newspaper_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),                        # базовое для админ панели
    path('users/', include('users.urls')),                  # new1 приложение абстрактное для авторизации
    path('users/', include('django.contrib.auth.urls')),    # new1 базовая авторизация
    path('articles/', include('articles.urls')),            # new4 еще не используется боковая панель для уведомления 
   # path('', TemplateView.as_view(template_name='home.html'), name='home' ), # new1 уже не используется
    path('', include('pages.urls')),                         # new стартовая страница
    path('testing/', include('testing.urls')),              # new приложение для тестирования
]

newspaper_project/pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(),  name='home'),     # new 2 , method_HomePageView(views) and link_home
]

newspaper_project/testing/urls.py
from django.urls import path

from .views import TestingPageView, ResultPageView

urlpatterns = [
    path('', TestingPageView.as_view(),  name='testing'),     # new 2 , method_HomePageView(views) and link_home
    path('result/', ResultPageView.as_view(),  name='result'),
]

newspaper_project/testing/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Question(models.Model):
    question_text = models.TextField(max_length=500, 
        verbose_name='Вопрос:')
    question_description = models.TextField(max_length=500, blank=True, 
        verbose_name='Описание вопроса:')
    image = models.ImageField(upload_to='static/testing/images', blank=True, 
        verbose_name='Картинка вопроса:')
    parent_nomer = models.IntegerField(default=0, unique=True, 
        verbose_name='Номер вопроса из документа:')
    pub_date = models.DateTimeField('date published') 
        
    def __str__(self):
        return self.question_text
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    # создание метки для paginator
    class Meta:
        verbose_name_plural = 'Вопросы'
        verbose_name = 'Вопрос'
        ordering = ['parent_nomer']

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField(max_length=500,
        verbose_name='Ответ:')
    votes = models.IntegerField(default=0,
        verbose_name='Правильно: 1 / не правильно: 0')

    def __str__(self):
        return self.choice_text


# результат
class Result(models.Model):
    # user
    user_text = models.CharField(max_length=150)                
    # время каждого вопроса на который он отвечал
    result_pub_date  = models.DateTimeField(auto_now_add=True, db_index=True)
    
    def __str__(self):
        return self.user_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    class Meta:
        verbose_name_plural = 'Результаты тестирования'

# описание результата
class ResultDescription(models.Model):
    result_user = models.ForeignKey(Result, on_delete=models.CASCADE)
    # номер по порядку
    d_id = models.IntegerField(default=0)
    # вопрос пользователю
    question_t = models.CharField(max_length=500)
    # ответ который выбрал пользователь
    question_choice= models.CharField(max_length=500, blank=True)
    # правильность ответа
    question_votes = models.CharField(max_length=30)
    # id вопроса для анализа ответа   
    nomer = models.IntegerField(default=0)

    def __str__(self):
        return self.question_t

newspaper_project/testing/views.py
from django.shortcuts import render
from django.views.generic import TemplateView   # new 2
# Create your views here.

class TestingPageView(TemplateView):       # inheritance in TemplateView
    template_name = 'testing/testing.html'


class ResultPageView(TemplateView):       # inheritance in TemplateView
    template_name = 'testing/result.html'

newspaper_project/testing/templates/testing/result.html
{% extends "base.html" %}

{% block content %}

<br>
<br>   
<div class="container mt-5">
    {% for result in results %}    
    <h4> Релультаты тестирования: {{ result.user_text }} дата {{ result.result_pub_date }}</h4>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Вопрос</th>
            <th scope="col">Ваш ответ</th>
            <th scope="col">правильно / не правильно</th>
          </tr>
        </thead>
        <tbody>
                  {% for resul  in result.resultdescription_set.all %}  
                  <tr> 
                  <th> {{ resul.d_id }}             </th>
                  <th> {{ resul.question_t }}       </th>
                  <th> {{ resul.question_choice }}  </th>
                  <th> {{ resul.question_votes }}   </th>
                  </tr>
                  {% endfor %} 
        </tbody>
      </table>    
      <br><br>
      {% endfor %}
</div>
{% endblock %}

newspaper_project/testing/templates/testing/testing.html
{% extends 'base.html' %}

{% block title %}Тестирование:{% endblock title %}

{% block content %}
    <div class="container mt-5">
    <h4 class="white typed">Комплекс тестовых вопросов 
                                              на соответствие квалификационным требованиям вне зависимости от области 
                                              и вида профессиональной служебной деятельности 
                                              (базовым квалификационным требованиям)</h4>

    <p>Имя: {{ user.username }} <br> Дата:</p>
    </div>

         


{% endblock content %}